# Generated by Django 5.0.6 on 2024-07-04 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='date_posted',
            new_name='date_and_time',
        ),
        migrations.RemoveField(
            model_name='object',
            name='title',
        ),
        migrations.AddField(
            model_name='object',
            name='file_format',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='file_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='object',
            name='permitted_users',
            field=models.ManyToManyField(related_name='permitted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object',
            name='size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='object',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
