# Generated by Django 5.0.6 on 2024-07-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='date_posted',
            new_name='date_and_time',
        ),
        migrations.RemoveField(
            model_name='object',
            name='title',
        ),
        migrations.AddField(
            model_name='object',
            name='file_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='object',
            name='size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
