# Generated by Django 5.0.6 on 2024-07-03 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='file_format',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='object',
            name='permitted_users',
            field=models.ManyToManyField(related_name='permitted_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='object',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
