# Generated by Django 5.0.6 on 2024-07-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_rename_date_posted_object_date_and_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
