# Generated by Django 5.0.6 on 2024-07-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='date_and_time',
        ),
    ]
